### ISSUE TITLE
Can't get extension to work

### ISSUE THREAD

**Issue by glass-w** [JethroHemmann/QuickLookProtein#1]
After downloading and installing the Quick Look Protein extension it doesn't appear when using the MacOS Quick Look feature.

OS details:

```
macOS Big Sur
version: 11.5.2
```

Checking the Uniform Type Identifier I get the following:

```
mdls -name kMDItemContentType 1xhz.pdb
kMDItemContentType = "dyn.ah62d4rv4ge81a3dc"
```

**Comment by JethroHemmann** [comment]
Thanks for the feedback! This UTI was not yet added to the extension. 
I will add it in the next release. 

In the meantime, you can also modify the corresponding entry in the `Info.plist` yourself. Just open the file `/Applications/QuickLookProtein.app/Contents/PlugIns/QuickLookProtein Extension.appex/Contents/Info.plist` in any text editor and add the UTI to the array in the key `QLSupportedContentTypes` as a string: `<string>dyn.ah62d4rv4ge81a3dc</string>`

You might need to reset quick look, but not sure about that: `qlmanage -r`

**Comment by glass-w** [comment]
I've added the string (and reset using `qlmanage -r`) but I don't seem to have any change, not sure why. Is there a `dev` branch you're working on? If I get something to work I'd be happy to make a PR there in the future.

**Comment by JethroHemmann** [comment]
I realized that messing with the `Info.plist` file manually might not work (anymore), I guess due to code signing. 

I therefore created a new release, v1.1 where the new UTI is added. Hope this works for you!
https://github.com/JethroHemmann/QuickLookProtein/releases/tag/v1.1

**Comment by glass-w** [comment]
@JethroHemmann great, I've just installed `v1.1` and it works. Thanks for sorting that!
