### ISSUE TITLE
Big Sur 11.5+ required?

### ISSUE THREAD

**Issue by mariota20** [JethroHemmann/QuickLookProtein#2]
Hello.
Thanks for creating nice Quick Look extension.
I tried to run this on Big Sur 11.0, but it did not work properly. It closed immediately when I ran it.
After the OS upgrade to Big Sur 11.5, it works fine.
This may require Big Sur 11.5+.

**Comment by JethroHemmann** [comment]
Thanks for letting me know!

I built the code using macOS 11.0 as target, so in principal it should work on that version. As I don't have an old macOS version installed, I unfortunately can not test it properly.

I will add a note to the documentation.
