### ISSUE TITLE
Default viewing mode based on filetype

### ISSUE THREAD

**Issue by jgassens** [JethroHemmann/QuickLookProtein#3]
Love this plugin! I've noticed that for CIF files, which are usually small molecules, they don't display correctly in "Ribbon" format. Likewise, PDB files, which are usually proteins, are tough to interpret on anything other than ribbon mode. Would it be possible to set a default for each file type… e.g. "stick" for CIF files and "ribbon" for PDB files?

**Comment by JethroHemmann** [comment]
Thanks for the feedback!

Indeed, this is something I was also think about. Separate default settings for each file type would be the best solution and should be possible to implement. I will give it a try when I have some time (might take a few weeks though).

**Comment by JethroHemmann** [comment]
I created now a new release (v1.3) which allows to set display style for each file type separately: https://github.com/JethroHemmann/QuickLookProtein/releases/tag/v1.3

Hope this helps and is what you wanted!

**Comment by jgassens** [comment]
This is great! I’ve Tweeted your praises! Keep up the good work.

jeremiah


From: Jethro Hemmann ***@***.***>
Date: Tuesday, May 3, 2022 at 4:32 PM
To: JethroHemmann/QuickLookProtein ***@***.***>
Cc: jgassens ***@***.***>, Author ***@***.***>
Subject: Re: [JethroHemmann/QuickLookProtein] Default viewing mode based on filetype (Issue #3)

I created now a new release (v1.3) which allows to set display style for each file type separately: https://github.com/JethroHemmann/QuickLookProtein/releases/tag/v1.3

Hope this helps and is what you wanted!
