### ISSUE TITLE
Does not open cif files

### ISSUE THREAD

**Issue by harripj** [JethroHemmann/QuickLookProtein#6]
Hi there, firstly I wanted to say this sounds like a great quicklook extension!

I tried to open a `.cif` file on my computer but it seems the plugin does not register. I should mention that I had CrystalMaker installed and it would seem that quicklook is defaulting to that program, even though it doesn't have a specific quicklook extension (as far as I am aware).

For the file in question:
```
>>> mdls -name kMDItemContentType GaAs_mp-2534_computed.ci:

kMDItemContentType = "com.crystalmaker.crystalmaker.cif"
```

The file itself is from MaterialsProject: https://materialsproject.org/materials/mp-2534/

If you have any suggestions I would love to give this app a try!

**Comment by JethroHemmann** [comment]
Thanks for the feedback and sorry for the late reply, I was in vacation. 

This should however be easy to fix. I will just need to add the UTI `com.crystalmaker.crystalmaker.cif` to the extension. Will do so in the next release. I will keep you posted!

**Comment by harripj** [comment]
> Thanks for the feedback and sorry for the late reply, I was in vacation.

No problem!

> This should however be easy to fix. I will just need to add the UTI com.crystalmaker.crystalmaker.cif to the extension. Will do so in the next release. I will keep you posted!

Looking forward to it!

**Comment by JethroHemmann** [comment]
Hi Paddy, 

I now added the new UTI to the latest release v1.4. You can find it here: https://github.com/JethroHemmann/QuickLookProtein/releases/tag/v1.4

Hope now it works for you!

**Comment by harripj** [comment]
@JethroHemmann This update works for me, very cool app, and makes it easy to check through `.cif` files!
